# Generated by Django 5.2.8 on 2025-12-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0005_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
